(() => {
'use strict';const C=window.NWLClassifier,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],KEY='needwantlater.items.v1';
let items;try{items=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{items=[]}
// The app was never released with real user data before this migration: clear the entire legacy seeded store once.
if(!localStorage.getItem('needwantlater.clean-start.v3')){items=[];localStorage.setItem(KEY,'[]');localStorage.setItem('needwantlater.clean-start.v3','1')}
let editingId=null,preview=null,detailType=null,timer=null;const save=()=>localStorage.setItem(KEY,JSON.stringify(items)),active=()=>items.filter(x=>!x.closed),esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),label=t=>t==='need'?'NEED':t==='want'?'WANT':'LATER';
function render(){const a=active();$('#totalCount').textContent=a.length;$('#typeSummary').innerHTML=['need','want','later'].map(t=>`<div class="type-stat ${t}"><strong>${a.filter(x=>x.type===t).length}</strong><span>${label(t)}</span><small>${t==='need'?'нужно':t==='want'?'хочу':'потом'}</small></div>`).join('');const priced=a.filter(x=>Number.isFinite(x.priceMin)&&Number.isFinite(x.priceMax)),mn=priced.reduce((s,x)=>s+x.priceMin,0),mx=priced.reduce((s,x)=>s+x.priceMax,0),fmt=n=>n>=1000000?`${(n/1000000).toFixed(n%1000000?1:0)}M`:n>=1000?`${Math.round(n/1000)}K`:n;$('#moneySummary').textContent=!priced.length?'0 ₽':mn===mx?`≈${fmt(mn)} ₽`:`≈${fmt(mn)}–${fmt(mx)} ₽`;$('#unknownSummary').textContent=`${a.length-priced.length} без оценки`;renderBoard();renderSearch();renderClosed()}
function renderBoard(){const b=$('#board'),groups=[['need','Сначала важное'],['want','Хочу'],['later','На потом']];b.innerHTML=groups.map(([t,n])=>{const g=active().filter(x=>x.type===t);return g.length?`<section class="board-section"><div class="board-head"><div class="board-title ${t}">${label(t)} <span class="count-pill">${g.length}</span></div><span class="sort-note">${n}</span></div><div class="card-grid">${g.map(card).join('')}</div></section>`:''}).join('')||`<section class="empty-home"><div class="empty-blob"><span>＋</span></div><h2>Пока пусто</h2><p>Добавляй сюда то, что нужно, хочется<br>или можно оставить на потом.</p><button class="empty-add" id="emptyAdd">＋ <span>Добавить первую вещь</span></button></section>`;$('#emptyAdd')?.addEventListener('click',startAdd);$$('.item-card',b).forEach(e=>e.addEventListener('click',()=>openDetail(e.dataset.id)))}
function card(x){return `<article class="item-card ${x.type}" data-id="${esc(x.id)}" style="--c1:${esc(x.c1||'#163d37')};--c2:${esc(x.c2||'#09161b')}"><div class="card-icon">${esc(x.icon||'◌')}</div><h3 class="card-title">${esc(x.title)}</h3><div class="card-price">${esc(x.priceText==='цена неизвестна'?'цена ?':x.priceText||'цена ?')}</div><div class="card-footer"><span>${label(x.type)}${x.category?' · '+esc(x.category):''}</span><b>→</b></div></article>`}
function row(x){return `<article class="list-row" data-id="${esc(x.id)}"><div class="list-row-icon">${esc(x.icon||'◌')}</div><div class="list-row-main"><strong>${esc(x.title)}</strong><span>${label(x.type)} · ${esc(x.category)} · ${esc(x.priceText||'цена ?')}</span></div><span>›</span></article>`}
function renderSearch(){const q=$('#searchInput').value.trim().toLowerCase(),p=active().filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q));$('#searchResults').innerHTML=p.length?p.map(row).join(''):'<div class="empty-state">Здесь пока ничего нет.</div>';$$('.list-row',$('#searchResults')).forEach(e=>e.onclick=()=>openDetail(e.dataset.id))}function renderClosed(){const p=items.filter(x=>x.closed);$('#closedList').innerHTML=p.length?p.map(row).join(''):'<div class="empty-state">Закрытых вещей пока нет.</div>';$$('.list-row',$('#closedList')).forEach(e=>e.onclick=()=>openDetail(e.dataset.id))}
function show(n){$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-item[data-view]').forEach(v=>v.classList.remove('active'));$(`#${n}View`).classList.add('active');$(`.nav-item[data-view="${n}"]`)?.classList.add('active')}function openSheet(s){$('#sheetBackdrop').hidden=false;s.hidden=false;document.body.style.overflow='hidden'}function close(){ $('#sheetBackdrop').hidden=true;$$('.bottom-sheet').forEach(s=>s.hidden=true);document.body.style.overflow=''}function startAdd(){preview=null;$('#quickInput').value='';$('#captureStep').classList.add('active');$('#previewStep').classList.remove('active');openSheet($('#addSheet'));setTimeout(()=>$('#quickInput').focus(),100)}
function analyze(){const t=$('#quickInput').value.trim();if(!t)return toast('Напиши, что у тебя на уме');preview=C.classify(t);fill(preview);$('#captureStep').classList.remove('active');$('#previewStep').classList.add('active')}function fill(x){$('#previewIcon').textContent=x.icon;$('#previewType').textContent=label(x.type);$('#previewTitleText').textContent=x.title;$('#previewCategoryText').textContent=x.category;$('#previewTitleInput').value=x.title;$('#previewPriceInput').value=x.priceText==='цена неизвестна'?'':x.priceText;$('#previewCategoryInput').value=x.category;$('#previewNextInput').value=x.next;$$('[data-type-choice]').forEach(b=>b.classList.toggle('selected',b.dataset.typeChoice===x.type))}
function submit(e){e.preventDefault();const raw=$('#previewPriceInput').value.trim(),p=raw?C.parsePriceInput(raw):{kind:'unknown',min:null,max:null,raw:'цена неизвестна'},cat=$('#previewCategoryInput').value.trim()||preview.category,[c1,c2]=C.palette(preview.type,cat);items.unshift({id:crypto.randomUUID?.()||Date.now()+'',...preview,title:$('#previewTitleInput').value.trim(),category:cat,priceText:p.kind==='unknown'?'цена неизвестна':p.raw,priceMin:p.min,priceMax:p.max,next:$('#previewNextInput').value.trim(),c1,c2,createdAt:Date.now(),closed:false});save();render();close();show('overview');toast('Добавлено')}
function openDetail(id){const x=items.find(i=>i.id===id);if(!x)return;editingId=id;detailType=x.type;$('#detailMeta').textContent=`${label(x.type)} · ${x.category}`;$('#detailTitle').textContent=x.title;$('#detailVisual').textContent=x.icon;$('#detailTitleInput').value=x.title;$('#detailPriceInput').value=x.priceText==='цена неизвестна'?'':x.priceText;$('#detailCategoryInput').value=x.category;$('#detailNextInput').value=x.next||'';$('#detailNoteInput').value=x.note||'';$('#toggleClosed').textContent=x.closed?'Вернуть в активные':'Закрыть';$$('[data-detail-type]').forEach(b=>b.classList.toggle('selected',b.dataset.detailType===x.type));openSheet($('#detailSheet'))}
function saveDetail(e){e.preventDefault();const x=items.find(i=>i.id===editingId),raw=$('#detailPriceInput').value.trim(),p=raw?C.parsePriceInput(raw):{kind:'unknown',min:null,max:null,raw:'цена неизвестна'};Object.assign(x,{title:$('#detailTitleInput').value.trim(),type:detailType,category:$('#detailCategoryInput').value.trim(),priceText:p.kind==='unknown'?'цена неизвестна':p.raw,priceMin:p.min,priceMax:p.max,next:$('#detailNextInput').value.trim(),note:$('#detailNoteInput').value.trim()});save();render();close();toast('Сохранено')}function toggle(){const x=items.find(i=>i.id===editingId);x.closed=!x.closed;save();render();close()}function del(){if(!confirm('Удалить эту вещь?'))return;items=items.filter(x=>x.id!==editingId);save();render();close()}function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),1500)}
$$('.nav-item[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#openAdd').onclick=startAdd;$('#analyzeButton').onclick=analyze;$('#backToCapture').onclick=()=>{$('#previewStep').classList.remove('active');$('#captureStep').classList.add('active')};$('#previewStep').onsubmit=submit;$$('[data-type-choice]').forEach(b=>b.onclick=()=>{preview.type=b.dataset.typeChoice;fill(preview)});$$('[data-detail-type]').forEach(b=>b.onclick=()=>{detailType=b.dataset.detailType;$$('[data-detail-type]').forEach(v=>v.classList.toggle('selected',v===b))});$('#detailForm').onsubmit=saveDetail;$('#toggleClosed').onclick=toggle;$('#deleteItem').onclick=del;$('#searchInput').oninput=renderSearch;$$('[data-close-sheet]').forEach(b=>b.onclick=close);$('#sheetBackdrop').onclick=close;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();