(() => {
  'use strict';
  const C = window.NWLClassifier;
  const STORAGE_KEY = 'needwantlater.items.v1';
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];

  let items = loadItems();
  let editingId = null;
  let preview = null;
  let detailType = null;
  let toastTimer = null;

  // Remove demo data shipped in the first MVP once. User-created data is kept.
  const DEMO_TITLES = new Set(['Удалить зубы мудрости','Очки','Новый телефон','Поставить брекеты','Мониторы в студию','Новая куртка','Татуировка','Путешествие в Исландию','Проектор для дома','Гитара Fender Telecaster']);
  if (!localStorage.getItem('needwantlater.demo-cleanup.v2')) {
    items = items.filter(x => !DEMO_TITLES.has(x.title));
    localStorage.setItem('needwantlater.demo-cleanup.v2','1');
    saveItems();
  }

  function loadItems(){ try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]} }
  function saveItems(){localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}
  function activeItems(){return items.filter(x=>!x.closed)}
  function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function typeLabel(t){return t==='need'?'NEED':t==='want'?'WANT':'LATER'}
  function typeRu(t){return t==='need'?'нужно':t==='want'?'хочу':'потом'}
  function render(){renderSummary();renderBoard();renderSearch();renderClosed()}
  function renderSummary(){const a=activeItems();$('#totalCount').textContent=a.length;$('#typeSummary').innerHTML=['need','want','later'].map(t=>`<div class="type-stat ${t}"><strong>${a.filter(x=>x.type===t).length}</strong><span>${typeLabel(t)}</span><small>${typeRu(t)}</small></div>`).join('');const k=a.filter(x=>Number.isFinite(x.priceMin)&&Number.isFinite(x.priceMax));const min=k.reduce((s,x)=>s+x.priceMin,0),max=k.reduce((s,x)=>s+x.priceMax,0);$('#moneySummary').textContent=k.length?moneySummary(min,max):'0 ₽';const u=a.length-k.length;$('#unknownSummary').textContent=u?`${u} без оценки`:'0 без оценки'}
  function moneySummary(min,max){const f=n=>n>=1000000?`${(n/1000000).toFixed(n%1000000?1:0)}M`:n>=1000?`${Math.round(n/1000)}K`:String(n);return min===max?`≈${f(min)} ₽`:`≈${f(min)}–${f(max)} ₽`}
  function renderBoard(){const board=$('#board'),groups=[['need','Сначала важное'],['want','Хочу'],['later','На потом']];board.innerHTML=groups.map(([t,n])=>{const g=activeItems().filter(x=>x.type===t).sort(sortForBoard);if(!g.length)return'';return `<section class="board-section"><div class="board-head"><div class="board-title ${t}">${typeLabel(t)} <span class="count-pill">${g.length}</span></div><span class="sort-note">${n}</span></div><div class="card-grid">${g.map((x,i)=>cardHTML(x,i)).join('')}</div></section>`}).join('')||`<section class="empty-home"><div class="empty-blob" aria-hidden="true"><span>＋</span></div><h2>Пока пусто</h2><p>Добавляй сюда то, что нужно, хочется<br>или можно оставить на потом.</p><button class="empty-add" id="emptyAdd">＋ <span>Добавить первую вещь</span></button></section>`;$('#emptyAdd')?.addEventListener('click',startAdd);$$('.item-card',board).forEach(el=>el.addEventListener('click',e=>{if(!e.target.closest('.card-menu'))openDetail(el.dataset.id)}));$$('.card-menu',board).forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openDetail(b.closest('.item-card').dataset.id)}))}
  function sortForBoard(a,b){const ak=Number.isFinite(a.priceMax),bk=Number.isFinite(b.priceMax);if(ak&&bk)return(b.priceMax||0)-(a.priceMax||0);if(ak!==bk)return ak?-1:1;return(b.createdAt||0)-(a.createdAt||0)}
  function cardHTML(x,i){return `<article class="item-card" data-id="${esc(x.id)}" style="--c1:${esc(x.c1||'#6436b6')};--c2:${esc(x.c2||'#173b51')}"><div class="liquid-glow"></div><button class="card-menu">•••</button><div class="card-content"><div class="card-icon">${esc(x.icon||'◌')}</div><h3 class="card-title">${esc(x.title)}</h3><span class="card-chip">${typeLabel(x.type)} · ${esc(x.category)}</span><div class="card-price">${esc(x.priceText||'цена неизвестна')}</div></div><div class="card-action"><span class="action-arrow">→</span><span>${esc(x.next||'Посмотреть варианты')}</span></div></article>`}
  function renderSearch(){const q=($('#searchInput').value||'').trim().toLowerCase(),p=activeItems().filter(x=>!q||[x.title,x.category,x.next,x.priceText].join(' ').toLowerCase().includes(q));$('#searchResults').innerHTML=p.length?p.map(rowHTML).join(''):`<div class="empty-state">Здесь пока ничего нет.</div>`;$$('.list-row',$('#searchResults')).forEach(el=>el.addEventListener('click',()=>openDetail(el.dataset.id)))}
  function renderClosed(){const p=items.filter(x=>x.closed).sort((a,b)=>(b.closedAt||0)-(a.closedAt||0));$('#closedList').innerHTML=p.length?p.map(rowHTML).join(''):`<div class="empty-state">Закрытых вещей пока нет.</div>`;$$('.list-row',$('#closedList')).forEach(el=>el.addEventListener('click',()=>openDetail(el.dataset.id)))}
  function rowHTML(x){return `<article class="list-row" data-id="${esc(x.id)}"><div class="list-row-icon">${esc(x.icon||'◌')}</div><div class="list-row-main"><strong>${esc(x.title)}</strong><span>${typeLabel(x.type)} · ${esc(x.category)} · ${esc(x.priceText||'цена неизвестна')}</span></div><span>›</span></article>`}
  function showView(n){$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-item[data-view]').forEach(b=>b.classList.remove('active'));$(`#${n}View`).classList.add('active');$(`.nav-item[data-view="${n}"]`)?.classList.add('active');if(n==='search')setTimeout(()=>$('#searchInput').focus(),100)}
  function openSheet(s){$('#sheetBackdrop').hidden=false;s.hidden=false;document.body.style.overflow='hidden'}function closeSheets(){$('#sheetBackdrop').hidden=true;$$('.bottom-sheet').forEach(s=>s.hidden=true);document.body.style.overflow=''}
  function startAdd(){preview=null;$('#quickInput').value='';$('#captureStep').classList.add('active');$('#previewStep').classList.remove('active');openSheet($('#addSheet'));setTimeout(()=>$('#quickInput').focus(),120)}
  function analyzeInput(){const text=$('#quickInput').value.trim();if(!text){toast('Напиши, что у тебя на уме');return}preview=C.classify(text);preview.sourceText=text;fillPreview(preview);$('#captureStep').classList.remove('active');$('#previewStep').classList.add('active')}
  function fillPreview(x){$('#previewIcon').textContent=x.icon;$('#previewType').textContent=typeLabel(x.type);$('#previewTitleText').textContent=x.title;$('#previewCategoryText').textContent=x.category;$('#previewTitleInput').value=x.title;$('#previewPriceInput').value=x.priceText==='цена неизвестна'?'':x.priceText;$('#previewCategoryInput').value=x.category;$('#previewNextInput').value=x.next;$$('[data-type-choice]').forEach(b=>b.classList.toggle('selected',b.dataset.typeChoice===x.type))}
  function setPreviewType(t){if(!preview)return;preview.type=t;const[c1,c2]=C.palette(t,preview.category);preview.c1=c1;preview.c2=c2;fillPreview({...preview,title:$('#previewTitleInput').value,priceText:$('#previewPriceInput').value||'цена неизвестна',category:$('#previewCategoryInput').value,next:$('#previewNextInput').value})}
  function submitPreview(e){e.preventDefault();if(!preview)return;const raw=$('#previewPriceInput').value.trim(),p=raw?C.parsePriceInput(raw):{kind:'unknown',min:null,max:null,raw:'цена неизвестна'},category=$('#previewCategoryInput').value.trim()||preview.category,[c1,c2]=C.palette(preview.type,category);items.unshift({id:crypto.randomUUID?crypto.randomUUID():`i-${Date.now()}`,...preview,title:$('#previewTitleInput').value.trim(),category,priceText:p.kind==='unknown'?(raw||'цена неизвестна'):p.raw,priceMin:p.min,priceMax:p.max,next:$('#previewNextInput').value.trim()||'Посмотреть варианты',c1,c2,createdAt:Date.now(),closed:false});saveItems();render();closeSheets();showView('overview');toast('Добавлено')}
  function openDetail(id){const x=items.find(i=>i.id===id);if(!x)return;editingId=id;detailType=x.type;$('#detailMeta').textContent=`${typeLabel(x.type)} · ${x.category}`;$('#detailTitle').textContent=x.title;$('#detailVisual').textContent=x.icon||'◌';$('#detailVisual').style.background=`linear-gradient(145deg,${x.c1||'#4b2497'},${x.c2||'#162a60'})`;$('#detailTitleInput').value=x.title;$('#detailPriceInput').value=x.priceText==='цена неизвестна'?'':x.priceText;$('#detailCategoryInput').value=x.category;$('#detailNextInput').value=x.next||'';$('#detailNoteInput').value=x.note||'';$('#toggleClosed').textContent=x.closed?'Вернуть в активные':'Закрыть';$$('[data-detail-type]').forEach(b=>b.classList.toggle('selected',b.dataset.detailType===x.type));openSheet($('#detailSheet'))}
  function submitDetail(e){e.preventDefault();const x=items.find(i=>i.id===editingId);if(!x)return;const category=$('#detailCategoryInput').value.trim()||'Личное',raw=$('#detailPriceInput').value.trim(),p=raw?C.parsePriceInput(raw):{kind:'unknown',min:null,max:null,raw:'цена неизвестна'},cat=C.inferCategory(category+' '+$('#detailTitleInput').value),[c1,c2]=C.palette(detailType,category);Object.assign(x,{title:$('#detailTitleInput').value.trim(),type:detailType,category,icon:cat.score?cat.icon:x.icon,priceText:p.kind==='unknown'?(raw||'цена неизвестна'):p.raw,priceMin:p.min,priceMax:p.max,next:$('#detailNextInput').value.trim(),note:$('#detailNoteInput').value.trim(),c1,c2});saveItems();render();closeSheets();toast('Сохранено')}
  function toggleClosed(){const x=items.find(i=>i.id===editingId);if(!x)return;x.closed=!x.closed;x.closedAt=x.closed?Date.now():null;saveItems();render();closeSheets();toast(x.closed?'Закрыто':'Возвращено')}
  function deleteCurrent(){if(!editingId||!confirm('Удалить эту вещь?'))return;items=items.filter(x=>x.id!==editingId);saveItems();render();closeSheets();toast('Удалено')}
  function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1600)}
  $$('.nav-item[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('#openAdd').addEventListener('click',startAdd);$('#analyzeButton').addEventListener('click',analyzeInput);$('#quickInput').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')analyzeInput()});$('#backToCapture').addEventListener('click',()=>{$('#previewStep').classList.remove('active');$('#captureStep').classList.add('active')});$('#previewStep').addEventListener('submit',submitPreview);$$('[data-type-choice]').forEach(b=>b.addEventListener('click',()=>setPreviewType(b.dataset.typeChoice)));$$('[data-detail-type]').forEach(b=>b.addEventListener('click',()=>{detailType=b.dataset.detailType;$$('[data-detail-type]').forEach(x=>x.classList.toggle('selected',x===b))}));$('#detailForm').addEventListener('submit',submitDetail);$('#toggleClosed').addEventListener('click',toggleClosed);$('#deleteItem').addEventListener('click',deleteCurrent);$('#searchInput').addEventListener('input',renderSearch);$$('[data-close-sheet]').forEach(b=>b.addEventListener('click',closeSheets));$('#sheetBackdrop').addEventListener('click',closeSheets);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheets()});render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();